name: Setup Node & PNPM

inputs:
  cache:
    description: Cache the PNPM store in the GitHub Actions cache. Defaults to `true`.
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Setup PNPM
      uses: pnpm/action-setup@v4

    - name: Setup Node
      uses: actions/setup-node@v5
      with:
        node-version-file: .node-version
        package-manager-cache: false

    - name: Locate PNPM store
      id: pnpm
      shell: bash
      run: echo "store-path=$(pnpm store path)" >> $GITHUB_OUTPUT

    - name: Restore PNPM store
      id: restore
      uses: actions/cache/restore@v4
      with:
        path: ${{ steps.pnpm.outputs.store-path }}
        key: pnpm-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}

    - name: Verify Lockfile
      shell: bash
      if: ${{ !steps.restore.outputs.cache-hit }}
      run: pnpm install --lockfile-only --resolution-only

    - name: Install Dependencies
      shell: bash
      run: pnpm install --frozen-lockfile ${{ steps.restore.outputs.cache-hit && '--offline' || '' }}

    - name: Save PNPM store
      uses: actions/cache/save@v4
      if: ${{ inputs.cache == 'true' && !steps.restore.outputs.cache-hit }}
      with:
        path: ${{ steps.pnpm.outputs.store-path }}
        key: pnpm-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
